/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/': RouteRecordInfo<
      '/blog/',
      '/blog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/front-end/block': RouteRecordInfo<
      '/blog/front-end/block',
      '/blog/front-end/block',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/front-end/configure': RouteRecordInfo<
      '/blog/front-end/configure',
      '/blog/front-end/configure',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/front-end/foundation-npm': RouteRecordInfo<
      '/blog/front-end/foundation-npm',
      '/blog/front-end/foundation-npm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/front-end/gateway': RouteRecordInfo<
      '/blog/front-end/gateway',
      '/blog/front-end/gateway',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/front-end/git': RouteRecordInfo<
      '/blog/front-end/git',
      '/blog/front-end/git',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/front-end/mac-command': RouteRecordInfo<
      '/blog/front-end/mac-command',
      '/blog/front-end/mac-command',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/front-end/npm-package': RouteRecordInfo<
      '/blog/front-end/npm-package',
      '/blog/front-end/npm-package',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/front-end/npm-warehouse': RouteRecordInfo<
      '/blog/front-end/npm-warehouse',
      '/blog/front-end/npm-warehouse',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/front-end/responsive-layout': RouteRecordInfo<
      '/blog/front-end/responsive-layout',
      '/blog/front-end/responsive-layout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/front-end/seo': RouteRecordInfo<
      '/blog/front-end/seo',
      '/blog/front-end/seo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/front-end/vs-code': RouteRecordInfo<
      '/blog/front-end/vs-code',
      '/blog/front-end/vs-code',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/front-end/weakup': RouteRecordInfo<
      '/blog/front-end/weakup',
      '/blog/front-end/weakup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/front-end/website-perf': RouteRecordInfo<
      '/blog/front-end/website-perf',
      '/blog/front-end/website-perf',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/front-end/webssh': RouteRecordInfo<
      '/blog/front-end/webssh',
      '/blog/front-end/webssh',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/source-code-analysis/cli-spinners': RouteRecordInfo<
      '/blog/source-code-analysis/cli-spinners',
      '/blog/source-code-analysis/cli-spinners',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/source-code-analysis/husky': RouteRecordInfo<
      '/blog/source-code-analysis/husky',
      '/blog/source-code-analysis/husky',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/source-code-analysis/i18next': RouteRecordInfo<
      '/blog/source-code-analysis/i18next',
      '/blog/source-code-analysis/i18next',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/source-code-analysis/ora': RouteRecordInfo<
      '/blog/source-code-analysis/ora',
      '/blog/source-code-analysis/ora',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/source-code-analysis/read-source-code': RouteRecordInfo<
      '/blog/source-code-analysis/read-source-code',
      '/blog/source-code-analysis/read-source-code',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/system/mac-config': RouteRecordInfo<
      '/blog/system/mac-config',
      '/blog/system/mac-config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/system/nginx': RouteRecordInfo<
      '/blog/system/nginx',
      '/blog/system/nginx',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/system/ubuntu': RouteRecordInfo<
      '/blog/system/ubuntu',
      '/blog/system/ubuntu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/system/web-server-configuration': RouteRecordInfo<
      '/blog/system/web-server-configuration',
      '/blog/system/web-server-configuration',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/': RouteRecordInfo<
      '/home/',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/': RouteRecordInfo<
      '/tools/',
      '/tools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/wake_up/': RouteRecordInfo<
      '/tools/wake_up/',
      '/tools/wake_up',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/website/': RouteRecordInfo<
      '/website/',
      '/website',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/views/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/views/about.vue': {
      routes:
        | '/about'
      views:
        | never
    }
    'src/views/blog/index.vue': {
      routes:
        | '/blog/'
      views:
        | never
    }
    'src/blog/front-end/block.md': {
      routes:
        | '/blog/front-end/block'
      views:
        | never
    }
    'src/blog/front-end/configure.md': {
      routes:
        | '/blog/front-end/configure'
      views:
        | never
    }
    'src/blog/front-end/foundation-npm.md': {
      routes:
        | '/blog/front-end/foundation-npm'
      views:
        | never
    }
    'src/blog/front-end/gateway.md': {
      routes:
        | '/blog/front-end/gateway'
      views:
        | never
    }
    'src/blog/front-end/git.md': {
      routes:
        | '/blog/front-end/git'
      views:
        | never
    }
    'src/blog/front-end/mac-command.md': {
      routes:
        | '/blog/front-end/mac-command'
      views:
        | never
    }
    'src/blog/front-end/npm-package.md': {
      routes:
        | '/blog/front-end/npm-package'
      views:
        | never
    }
    'src/blog/front-end/npm-warehouse.md': {
      routes:
        | '/blog/front-end/npm-warehouse'
      views:
        | never
    }
    'src/blog/front-end/responsive-layout.md': {
      routes:
        | '/blog/front-end/responsive-layout'
      views:
        | never
    }
    'src/blog/front-end/seo.md': {
      routes:
        | '/blog/front-end/seo'
      views:
        | never
    }
    'src/blog/front-end/vs-code.md': {
      routes:
        | '/blog/front-end/vs-code'
      views:
        | never
    }
    'src/blog/front-end/weakup.md': {
      routes:
        | '/blog/front-end/weakup'
      views:
        | never
    }
    'src/blog/front-end/website-perf.md': {
      routes:
        | '/blog/front-end/website-perf'
      views:
        | never
    }
    'src/blog/front-end/webssh.md': {
      routes:
        | '/blog/front-end/webssh'
      views:
        | never
    }
    'src/blog/source-code-analysis/cli-spinners.md': {
      routes:
        | '/blog/source-code-analysis/cli-spinners'
      views:
        | never
    }
    'src/blog/source-code-analysis/husky.md': {
      routes:
        | '/blog/source-code-analysis/husky'
      views:
        | never
    }
    'src/blog/source-code-analysis/i18next.md': {
      routes:
        | '/blog/source-code-analysis/i18next'
      views:
        | never
    }
    'src/blog/source-code-analysis/ora.md': {
      routes:
        | '/blog/source-code-analysis/ora'
      views:
        | never
    }
    'src/blog/source-code-analysis/read-source-code.md': {
      routes:
        | '/blog/source-code-analysis/read-source-code'
      views:
        | never
    }
    'src/blog/system/mac-config.md': {
      routes:
        | '/blog/system/mac-config'
      views:
        | never
    }
    'src/blog/system/nginx.md': {
      routes:
        | '/blog/system/nginx'
      views:
        | never
    }
    'src/blog/system/ubuntu.md': {
      routes:
        | '/blog/system/ubuntu'
      views:
        | never
    }
    'src/blog/system/web-server-configuration.md': {
      routes:
        | '/blog/system/web-server-configuration'
      views:
        | never
    }
    'src/views/home/index.vue': {
      routes:
        | '/home/'
      views:
        | never
    }
    'src/views/tools/index.vue': {
      routes:
        | '/tools/'
      views:
        | never
    }
    'src/views/tools/wake_up/index.vue': {
      routes:
        | '/tools/wake_up/'
      views:
        | never
    }
    'src/views/website/index.vue': {
      routes:
        | '/website/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
